# Huge service test config
{{$HUGE_SERVICE_HEADLESS := DefaultParam .CL2_HUGE_SERVICE_HEADLESS false}}
{{$HUGE_SERVICE_ENDPOINTS := DefaultParam .CL2_HUGE_SERVICE_ENDPOINTS 1000}}

## Other params
{{$ENABLE_DNSTEST := DefaultParam .CL2_ENABLE_DNSTESTS false}}

name: huge-service
namespace:
  number: 1
tuningSets:
- name: Sequence
  parallelismLimitedLoad:
    parallelismLimit: 1
steps:
- module:
    path: modules/measurements.yaml
    params:
      action: start
{{if $ENABLE_DNSTEST}}
- module:
    path: modules/dnsperfgo.yaml
    params:
      action: create
{{end}}
- module:
    path: modules/service.yaml
    params:
      endpoints: {{$HUGE_SERVICE_ENDPOINTS}}
      isHeadless: {{$HUGE_SERVICE_HEADLESS}}
      serviceName: huge-service
{{if $ENABLE_DNSTEST}}
- module:
    path: modules/dnsperfgo.yaml
    params:
      action: gather
{{end}}
- module:
    path: modules/measurements.yaml
    params:
      action: gather
