{{$endpoints := .endpoints}}
{{$isHeadless := .isHeadless}}
{{$serviceName := .serviceName}}

## CL2 params
{{$CHECK_IF_PODS_ARE_UPDATED := DefaultParam .CL2_CHECK_IF_PODS_ARE_UPDATED true}}
# For very large number of pods it is better to split creating them into
# deployments. The number of pods in each such deployment should be a divisor
# of the total number of pods.
{{$HUGE_SERVICE_PODS_PER_DEPLOYMENT := DefaultParam .CL2_HUGE_SERVICE_PODS_PER_DEPLOYMENT 1000}}

{{$deployments := DivideInt $endpoints $HUGE_SERVICE_PODS_PER_DEPLOYMENT}}

steps:
- name: Create {{$serviceName}}
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: {{$serviceName}}
      objectTemplatePath: service.yaml
      templateFillMap:
        HeadlessService: {{$isHeadless}}
- name: Creating {{$serviceName}} measurements
  measurements:
  - Identifier: WaitForHugeServiceDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: apps/v1
      checkIfPodsAreUpdated: {{$CHECK_IF_PODS_ARE_UPDATED}}
      kind: Deployment
      labelSelector: group = {{$serviceName}}
      operationTimeout: 20m
- name: Creating {{$serviceName}} pods
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: {{$deployments}}
    tuningSet: Sequence
    objectBundle:
    - basename: huge-service-deployment
      objectTemplatePath: simple-deployment.yaml
      templateFillMap:
        Replicas: {{$HUGE_SERVICE_PODS_PER_DEPLOYMENT}}
        Group: huge-service
        CpuRequest: 1m
        MemoryRequest: 10M
        SvcName: {{$serviceName}}
- name: Waiting for {{$serviceName}} pods to be created
  measurements:
  - Identifier: WaitForHugeServiceDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
- name: Deleting {{$serviceName}} pods
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: huge-service-deployment
      objectTemplatePath: simple-deployment.yaml
      templateFillMap:
        Replicas: {{$endpoints}}
        Group: {{$serviceName}}
        CpuRequest: 1m
        MemoryRequest: 10M
        SvcName: {{$serviceName}}
- name: Waiting for {{$serviceName}} pods to be deleted
  measurements:
  - Identifier: WaitForHugeServiceDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
- name: Delete {{$serviceName}}
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 0
    tuningSet: Sequence
    objectBundle:
    - basename: {{$serviceName}}
      objectTemplatePath: service.yaml
      templateFillMap:
        HeadlessService: {{$isHeadless}}
