{{$image := DefaultParam .CL2_BENCHMARK_IMAGE "gcr.io/k8s-testimages/perf-tests-util/request-benchmark:latest"}}
{{$inflight := DefaultParam .CL2_BENCHMARK_INFLIGHT 10}}
{{$uri := DefaultParam .CL2_BENCHMARK_URI "/api/v1/namespaces/%namespace%/pods"}}
{{$cpu := DefaultParam .CL2_BENCHMARK_POD_CPU "500m"}}
{{$memory := DefaultParam .CL2_BENCHMARK_POD_MEMORY "100Mi"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: benchmark
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        name: {{.Name}}
        group: benchmark
    spec:
      containers:
      - name: {{.Name}}
        image: {{$image}}
        imagePullPolicy: Always
        args:
        - --inflight={{$inflight}}
        - --namespace={{.Namespace}}
        - --uri={{$uri}}
        - --debug
        resources:
          requests:
            cpu: {{$cpu}}
            memory: {{$memory}}
